### ISSUE TITLE
API Portal -Display's limited amount of SharePoint Site folders (30)

### ISSUE THREAD

**Issue by Kaveerp** [nielsengelen/vbo365-rest#65]
Hi Nielsengelen

Please be advised that our SharePoint sites has several folders however when I logon to the API Portal, I cannot view more than 30 folders, I have tried searching the files on the "Filter by item" however I cannot find them in the filter.

Please can you advise and look into this.

Kind Regards

**Comment by crollorc** [comment]
We've seen the same issue. 

Perhaps 'Load more items' should load the next X documents or folders if they exist?

**Comment by Kaveerp** [comment]
Hi crollorc,

I cant see the 'Load more items' please advise where is this found ?

**Comment by nielsengelen** [comment]
Load more items is a button at the bottom of the grid but it's only available if there are more then 30 items/documents in the folder. It needs to be adjusted to also reflect folders (which is the issue you face now). I just verified this behavior as a bug / missing code. I most likely adjusted something (or removed too much code) which caused this bug. 

Thanks for reporting. I will update this thread with the solution (or updated file if needed/easier).

**Comment by Kaveerp** [comment]
> Load more items is a button at the bottom of the grid but it's only available if there are more then 30 items/documents in the folder. It needs to be adjusted to also reflect folders (which is the issue you face now). I just verified this behavior as a bug / missing code. I most likely adjusted something (or removed too much code) which caused this bug.
> 
> Thanks for reporting. I will update this thread with the solution (or updated file if needed/easier).

**Comment by Kaveerp** [comment]
> > Load more items is a button at the bottom of the grid but it's only available if there are more then 30 items/documents in the folder. It needs to be adjusted to also reflect folders (which is the issue you face now). I just verified this behavior as a bug / missing code. I most likely adjusted something (or removed too much code) which caused this bug.
> > Thanks for reporting. I will update this thread with the solution (or updated file if needed/easier).

Tha

**Comment by Kaveerp** [comment]
Hi nielsengelen 

Thank you for the feedback, looking forward to the solution.

Much appreciated.

**Comment by Kaveerp** [comment]
Hi nielsengelen

Have you managed to resolve this bug ?

Kind Regards

**Comment by nielsengelen** [comment]
@Kaveerp I expect the fix to be finished tomorrow. Thanks for your patience.

**Comment by Kaveerp** [comment]
Hi nielsengelen

Thank you , much much appreciated.

Kind Regards
Kaveer

**Comment by Kaveerp** [comment]
Hi nielsengelen

Sorry to bother you , please advise if you have the solution ?

Kind Regards
Kaveer

**Comment by nielsengelen** [comment]
I'm running extra tests to make sure no other bugs appear (never say never though). This issue also appears in OneDrive and Exchange so it's a bigger part to test/resolve.

**Comment by Kaveerp** [comment]
Hi nielsengelen

Thank you for advising , please let me know when you win..
Thank you once again for the feedback.

Kind Regards
Kaveer

**Comment by nielsengelen** [comment]
@Kaveerp this issue has been resolved for Exchange, OneDrive & SharePoint. You'll need to download a few files:
- veeam.class.php & veeam.php
- exchange.php, onedrive.php and sharepoint.php
- under css folder: style.css

Or you can do a git clone again (but first back up your config.php file so you can re-use it).

**Comment by Kaveerp** [comment]
Hi nielsengelen

Thank you , I will download the new files and advise you and the outcome.

Kind Regards
Kaveer

**Comment by Kaveerp** [comment]
Hi nielsengelen

Thank you for the Load more option however after testing I see that not all of the folders are populating even after clicking on the load more option I still don't see the folders.

Secondly each time I click on load more option, the folders start to duplicate themselves.

Please advise on why this is happening?

Kind Regards

Kaveer

**Comment by nielsengelen** [comment]
Hi Kaveer, please get the latest files (this duplicate bug was resolved yesterday after another report) and let me know if it is working.

**Comment by Kaveerp** [comment]
Hi Niels

Please advise which files is it, please provide me with the link?

Kind Regards
Kaveer

**Comment by nielsengelen** [comment]
@Kaveerp Sorry, I got confused there as this is for SharePoint. I will check if I can see what you are seeing and fix it.

**Comment by nielsengelen** [comment]
@Kaveerp Please download the veeam.php file and replace it in your installation. Can you let me know if this resolves the issue?

**Comment by nielsengelen** [comment]
Issue resolved in v4.2 update. If you are still facing issues, please reply here.
